### ISSUE TITLE
Inappropriate exit code on network operr.

### ISSUE THREAD

**Issue by zefie** [bemasher/rtlamr#110]
```
08:18:27.852721 main.go:179: operr: read tcp 127.0.0.1:39610->127.0.0.1:1234: read: connection reset by peer
zefie@server:~$ echo $?
0
```
How can I distinguish this from a successful -single run?

Extended details as to why I need this:

Trying to make a collectd system using rtlamr's output from my specific meter, however as we all know, rtl is a hack, and as such over time may crash.

For easier processing, saving power, and not burning out the dongle, the script only really runs rtlamr once every 60 seconds until it gets a reading (-single=true). rtl_tcp stays running but rtlamr does not. This increases the chances of it crashing honestly, but if I could get my error handling working it would be worth the savings.

There are still times where I will have to manually replug the dongle (or come up with some /sys hack to restart the dongle), but having rtlamr return an error code (besides success) when rtl_tcp fails can let me allow my script to start the process of restoring the radio (eg restart rtl_tcp daemon)

**Comment by parkerlreed** [comment]
What version are you using? Git errors out properly for me
````
[parker@stealth bin]$ ./rtlamr 
11:37:02.485655 main.go:81: Error connecting to spectrum server: dial tcp 127.0.0.1:1234: connect: connection refused
[parker@stealth bin]$ echo $?
1
````

**Comment by zefie** [comment]
... Why didn't I think to test on the command line, considering how collectd was behaving with my other scripts that worked on the CLI... I have tested as you have, and it does indeed return 0 in the command environment. My apologies, I will close this.

**Comment by bemasher** [comment]
Network operation errors occurring while reading from `rtl_tcp` are likely not returning appropriate exit codes because the error is logged and some tear-down occurs before rtlamr fully exits.

https://github.com/bemasher/rtlamr/blob/master/main.go#L178-L180

https://github.com/bemasher/rtlamr/blob/master/main.go#L153

https://github.com/bemasher/rtlamr/blob/master/main.go#L200-L204

https://github.com/bemasher/rtlamr/blob/master/main.go#L313

The error is not propagated up the stack to the main function, so no error is produced when rtlamr exits this way. I'll have a look at what it would take to give appropriate exit codes in this case.
