### ISSUE TITLE
Frequency spread

### ISSUE THREAD

**Issue by kostyan5** [bemasher/rtlamr#148]
Some of the supported meters have frequency ranges well beyond the bandwidth of RTL-SDR.  How does rtlamr able to receive those?  I read the frequency hopping issue and understand being able to decode any signal within the RTL SDR bandwidth (2.5MHz) but some of those meters have frequency ranges of 20MHz.

Does this mean that each of those meters hops through all those frequencies and eventually stumbles on the tuned range of RTL SDR?

**Comment by bemasher** [comment]
rtlamr will only receive messages transmitted in the receivable bandwidth of an rtlsdr, so messages by design, will be missed. Many meters do not update the information transmitted between every message, so this is not generally a problem. In the case of IDM packets, they transmit historical information, so complete usage history can be obtained from receiving a packet only once every few hours from a particular meter.

From my own observations, it appears that meters typically have pseudo-random hopping patterns that repeat, forever. So as you put it, yes, meters do just hop through each frequency and stumble into the bandwidth rtlamr is listening on.
