### ISSUE TITLE
No message received

### ISSUE THREAD

**Issue by 3dinhjeffrey** [bemasher/rtlamr#227]
Running on Raspberry pi 3b+

using 2 terminals, i ran 

# Terminal A
`$ rtl_tcp`

# Terminal B
`$ rtlamr`

i also tried with `rtlamr -msgtype=all -centerfreq=915M -samplerate=1382400`

on terminal A, I would get ll+, now 1 (all the way up to 502, then restarts)
on terminal B, nothing shows up.

Any advice? Thanks
<img width="561" alt="Screen Shot 2021-12-22 at 2 59 38 PM" src="https://user-images.githubusercontent.com/18014934/147166371-57090d04-587c-4a1a-9c28-808524eb5186.png">
<img width="566" alt="Screen Shot 2021-12-22 at 2 59 48 PM" src="https://user-images.githubusercontent.com/18014934/147166376-db46db6f-0f71-4891-8428-109ec7d08e73.png">

**Comment by bemasher** [comment]
A couple of things come to mind:

1. You probably don't have any rtlamr compatible meters.
2. Using `-msgtype=all` is likely causing rtl_tcp to build up linked lists of unconsumed samples because it includes the r900 decoder which is significantly less efficient than the other decoders and rtlamr isn't consuming samples fast enough.
3. You might try without the r900 decoder, and you may pick up some messages that were otherwise being missed.

**Comment by 3dinhjeffrey** [comment]
@bemasher Thank you for your response, really appreciate it

I ended up doing `rtlamr -msgtype=scm,scm+,idm -centerfreq=915M -samplerate=1382400`

I didn't get `ll+` messages anymore. but also didn't receive any meter messages. 

Couldn't find my meter ERT Type, but both my electricity and gas are ltron.

Electricity:
<img width="479" alt="Screen Shot 2021-12-22 at 10 32 07 PM" src="https://user-images.githubusercontent.com/18014934/147198519-10b92677-30e1-4646-9e27-438ba5f05feb.png">

Gas:
<img width="338" alt="Screen Shot 2021-12-22 at 10 30 34 PM" src="https://user-images.githubusercontent.com/18014934/147198346-0b6b8a2f-8cf8-4a5f-81a0-446705b20a20.png">

**Comment by Drizzt321** [comment]
I'm having a similar issue, don't see any messages coming in. Same exact meter, down to the FCC ID. Based on my reading from [this comment](https://github.com/bemasher/rtlamr/issues/83#issuecomment-352597248), it's sounds like my meter (mine is SoCal Edison) uses OpenWay and is probably encrypted? Or do I need to iterate through various frequencies to try and find what it's transmitting on?


```
$ go/bin/rtlamr -msgtype=scm,scm+,idm
14:35:46.044707 decode.go:45: CenterFreq: 912600155
14:35:46.044983 decode.go:46: SampleRate: 2359296
14:35:46.044991 decode.go:47: DataRate: 32768
14:35:46.044997 decode.go:48: ChipLength: 72
14:35:46.045002 decode.go:49: PreambleSymbols: 32
14:35:46.045007 decode.go:50: PreambleLength: 4608
14:35:46.045012 decode.go:51: PacketSymbols: 736
14:35:46.045017 decode.go:52: PacketLength: 105984
14:35:46.045042 decode.go:59: Protocols: scm,scm+,idm
14:35:46.045052 decode.go:60: Preambles: 111110010101001100000,0001011010100011,01010101010101010001011010100011
14:35:46.045070 main.go:126: GainCount: 29
```

**Comment by bemasher** [comment]
Feel free to try different frequencies, but most Itron meters I've seen use frequency hopping so you're pretty likely to hear something on the default frequency. If it's OpenWay, you're out of luck, this project doesn't support that.

**Comment by mwaterbu** [comment]
> If it's OpenWay, you're out of luck, this project doesn't support that.

Thank you for this information (now after searching I see that you have mentioned this on many issues over several years). After checking the list of [compatible meters](https://github.com/bemasher/rtlamr/wiki/Compatible-Meters), I was initially under the impression that mine would be supported, as I was blissfully unaware that OpenWay existed.

I had since tried a couple different USB RTL-SDR units, and various antennas, confused as to why I wasn't receiving any consumption messages, however, it appears this is because I probably don't have any rtlamr compatible meters.

@bemasher if you are aware of some meters which could be configured with OpenWay, such as the C2SOD, do you think it could make sense to mark them with an asterisk on the Compatible Meters page in the Wiki (with an explanation stating that if the meter has the OpenWay logo, it probably isn't going to work)? It may save some issues from being opened, as well as user's time.
