### ISSUE TITLE
Sorry for being dense, but is consumption coded or something?

### ISSUE THREAD

**Issue by jwvanderbeck** [bemasher/rtlamr#298]
I have an Itron 100G DLS, and I can successfully get readings that seem to correspond to my gas meter.  They have the same number identifier, is I remove the "12" from the front which I believe is correct.  So as I understand it I am seeing my readings.

However, the `consumption` value listed in these readings makes zero sense to me. It doesn't come even close to what is shown on the meter itself.

Right now I am seeing `consumption: 6110`.  My meter reads 0181 on the dials left to right. 

Do I need to "decode" the value provided somehow?

**Comment by jwvanderbeck** [comment]
Ok so this is actually me reading my meter wrong, and it being in a hard to read spot.  I took a photo of it then checked my bill where it says how to read the meter.

My meter actually reads 0061 which would be the 61 in the actual packets I'm seeing.  There are two dials on the bottom of the meter labeled "one dot" and "quarter dot" and I'm guessing that's where the 10 comes from?

**Comment by zachliu** [comment]
Not sure if this is related. Has your consumption reading ever increased?
I just got a new gas meter with Itron 100G DLS data logger (FCC ID: `EWQ100GDLRS`). It's been >>48 hours but the `"Consumption":200` never changed a bit.
Maybe they forgot to "activate" the data logger after installing the meter?

**Comment by sammarcus** [comment]
> My meter actually reads 0061 which would be the 61 in the actual packets I'm seeing.  There are two dials on the bottom of the meter labeled "one foot" and "quarter foot" and I'm guessing that's where the 10 comes from? 
> 
> 

@jwvanderbeck check out chapter 5 of [this guide](https://documents.dps.ny.gov/public/Common/ViewDoc.aspx?DocRefId=%7BC046A82A-6AF7-417D-860D-69296C974507%7D), it starts around page 28.

**Comment by jwvanderbeck** [comment]
Ah down and Nerdy, love it!

**Comment by jwvanderbeck** [comment]
> Not sure if this is related. Has your consumption reading ever increased? I just got a new gas meter with Itron 100G DLS data logger (FCC ID: `EWQ100GDLRS`). It's been >>48 hours but the `"Consumption":200` never changed a bit. Maybe they forgot to "activate" the data logger after installing the meter?

Yes my numbers have been going up.

**Comment by zachliu** [comment]
@sammarcus thanks man, but sadly that's not the module i have. it turns out my problem is far more "serious"...

for the new [Dresser series D gas meters](https://dresserutility.com/wp-content/uploads/NGS-MI-0039.pdf), the measuring part is also digital and controlled by an internal software, which transfers data to the Itron 100G DLS data logger, which then transmits on RF. 

while Itron 100G still transmits every 1 minute, the internal software only sends data every 100 cubic feet (1 CCF). so I'll never have accurate "real-time" gas usage monitoring on this meter :cry:

i've been long for the good ol 2-digit precision after decimal point since the meter upgrade...
