### ISSUE TITLE
CPU use

### ISSUE THREAD

**Issue by SergeiDelov** [bemasher/rtlamr#53]
FYI:
I tried rtlamr on Odroid U3.
For SCM messages CPU use was 8%, for R900 - 25%.
rtl_tcp -- 1..2%.

And one more -- I second for SCM and R900 messages in one output text stream.

I read you think about multiplex rtl_tcp... one more idea, though I think more CPU hungry -- option to use stdin/stdout to pipe irtl-tcp data through chained rtlamrs with each extracting specific  messages. 

Maybe such piping/chaining can be done even in one rtlamr process, in different threads?

Best regards,
Sergei.

**Comment by bemasher** [comment]
The R900 decoder is more CPU intensive because it requires three separate matched filters in order to decode all of the symbols the protocol's encoding scheme uses. As it is now, the R900 decoder piggy-backs on the decoder used for the rest of the protocols since it's preamble is manchester coded while the rest of it's payload uses 4-chip symbols.

I've decided against writing a multiplexed rtl_tcp. I've refactored some of the DSP functions and buffers such that it will be easier to use a single decoder with multiple (similar) protocols since the only real difference between protocols is the length of new sample blocks and how many samples to keep in the quantized buffer.

I'm closing this issue in favor of continuing the conversation on the existing ticket: #39
