### ISSUE TITLE
New ITRON AMI7 Meter

### ISSUE THREAD

**Issue by scoob8000** [bemasher/rtlamr#61]
Is there anything I can do to help add support for my electric meter?

It's an Itron AMI7.   FCCID SK9AMI7

Seems most meters in my area are this.   (Duquesne Light Company, Pittsburgh PA)

Thanks and keep up the great work!

**Comment by bemasher** [comment]
At this point I'm not prepared to develop or support OpenWay-based smart meters in rtlamr, primarily due to security implementation and lack of access to hardware for testing.

In the mean-time, there exist OpenWay compatible bridges which aren't unreasonably priced. Just be sure to contact your utility and verify compatibility *before* you purchase this, and look around, there are a few different manufacturers for devices like this: https://amzn.com/B00AII248U
