### ISSUE TITLE
Log File flag not working

### ISSUE THREAD

**Issue by vishwaslokesh** [bemasher/rtlamr#81]
The -logfile flag is not being accepted
Throws a error : flag provided but not defined: -logfile

Thanks

**Comment by kwd42** [comment]
That option was removed  Oct'16. Is it still in the documentation somewhere?
3fef2118f30633fede3f19c621e3f95c403736c7 @bemasher bemasher committed on Oct 6, 2016

**Comment by vishwaslokesh** [comment]
As the flag -format still shows up, saying the output will be written to the log file, I thought the option still exists.
Thanks for the quick response.

**Comment by kwd42** [comment]
Yes, the log file in this case is where ever you happen to send Stdout.

**Comment by bemasher** [comment]
The description string for `-format` is as follows since 2016-10-05, 3fef2118f30633fede3f19c621e3f95c403736c7:

`format to write log messages in: plain, csv, json, or xml`

It does not describe where messages are written, only the format they are written in. The only inaccuracy here is that they are not log messages as they are written to stdout rather than stderr.
